apiVersion: apps/v1
kind: Deployment
metadata:
  name:  k8s-static
  namespace: static
spec:
  selector:
    matchLabels:
      app: static
  replicas: 1
  template:
    metadata:
      labels:
        app: static
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  static
        image:  795118656430.dkr.ecr.us-east-2.amazonaws.com/k8s-static:K8s-StaticWebsite-12  
        ports:
        - containerPort:  80